version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: golden-postgres
    environment:
      POSTGRES_DB: golden_compass
      POSTGRES_USER: golden_user
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - golden-network

  redis:
    image: redis:7-alpine
    container_name: golden-redis
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    networks:
      - golden-network

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: golden-backend
    environment:
      - DATABASE_URL=postgresql://golden_user:${DB_PASSWORD}@postgres:5432/golden_compass
      - REDIS_URL=redis://redis:6379
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_MODEL=${OPENAI_MODEL}
      - ELEVENLABS_API_KEY=${ELEVENLABS_API_KEY}
      - ELEVENLABS_VOICE_ID=${ELEVENLABS_VOICE_ID}
      - PYTHONUNBUFFERED=1
    volumes:
      - ./backend:/app
      - ./media:/app/media
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis
    networks:
      - golden-network
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  celery:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: golden-celery
    environment:
      - DATABASE_URL=postgresql://golden_user:${DB_PASSWORD}@postgres:5432/golden_compass
      - REDIS_URL=redis://redis:6379
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_MODEL=${OPENAI_MODEL}
      - ELEVENLABS_API_KEY=${ELEVENLABS_API_KEY}
      - ELEVENLABS_VOICE_ID=${ELEVENLABS_VOICE_ID}
      - PYTHONUNBUFFERED=1
    volumes:
      - ./backend:/app
      - ./media:/app/media
    depends_on:
      - redis
      - postgres
      - backend
    networks:
      - golden-network
    command: celery -A app.core.celery_app worker --loglevel=info --pool=solo

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: golden-frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:5173"
    environment:
      - VITE_API_URL=http://localhost:8000
    networks:
      - golden-network
    depends_on:
      - backend

volumes:
  postgres_data:
  redis_data:

networks:
  golden-network:
    driver: bridge
